import {esc,attrs,icon} from '../lib/html.mjs';

export default page=>`<main id="main" class="subpage-main applications-page">
  <section class="page-hero" aria-labelledby="applications-page-heading"><div><span class="page-eyebrow">${esc(page.eyebrow)}</span><h1 id="applications-page-heading">${esc(page.heading)}</h1><p>${esc(page.lead)}</p></div><nav class="page-index" aria-label="Applications page sections"><a href="#application-areas">Research areas</a><a href="#regulatory-precedent">Regulatory context</a><a href="#applications-evidence">Evidence routes</a><a href="#applications-contact">Collaboration</a></nav></section>
  <section id="application-areas" class="page-section" aria-labelledby="application-areas-heading"><div class="section-heading"><span class="page-eyebrow">Research direction</span><h2 id="application-areas-heading">Where the veterinary questions begin.</h2></div><div class="application-grid">${page.areas.map(area=>`<article class="application-card"><span class="application-icon">${icon(area.icon)}</span><h3>${esc(area.title)}</h3><p>${esc(area.text)}</p></article>`).join('')}</div></section>
  <section id="regulatory-precedent" class="regulatory-feature" aria-labelledby="regulatory-heading"><div class="regulatory-marker"><span>1998</span><small>FDA veterinary precedent</small></div><div class="regulatory-copy"><span class="page-eyebrow">${esc(page.regulatory.eyebrow)}</span><h2 id="regulatory-heading">${esc(page.regulatory.title)}</h2>${page.regulatory.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="inline-actions"><a class="button" ${attrs(page.regulatory.primaryLink)}><span>${esc(page.regulatory.primaryLink.label)}</span>${icon('arrow')}</a><a class="text-link" ${attrs(page.regulatory.evidenceLink)}>${esc(page.regulatory.evidenceLink.label)} ${icon('arrow')}</a></div></div></section>
  <section id="applications-evidence" class="platform-band" aria-labelledby="applications-evidence-heading"><div><span class="page-eyebrow">${esc(page.evidence.eyebrow)}</span><h2 id="applications-evidence-heading">${esc(page.evidence.title)}</h2><p>${esc(page.evidence.text)}</p></div><div class="platform-actions"><a class="button" ${attrs(page.evidence.map)}><span>${esc(page.evidence.map.label)}</span>${icon('arrow')}</a><a class="platform-library-link" ${attrs(page.evidence.search)}><span>${esc(page.evidence.search.label)}</span>${icon('search')}</a></div></section>
  <section id="applications-contact" class="page-cta" aria-labelledby="applications-contact-heading"><div><span class="page-eyebrow">Research and partnerships</span><h2 id="applications-contact-heading">${esc(page.contact.title)}</h2><p>${esc(page.contact.text)}</p></div><a class="button" ${attrs(page.contact.link)}><span>${esc(page.contact.link.label)}</span>${icon('arrow')}</a></section>
</main>`;
