import {esc,icon} from '../lib/html.mjs';

export default page=>`<main id="main" class="subpage-main contact-page">
  <section class="page-hero" aria-labelledby="contact-page-heading"><div><span class="page-eyebrow">${esc(page.eyebrow)}</span><h1 id="contact-page-heading">${esc(page.heading)}</h1><p>${esc(page.lead)}</p></div></section>
  <section class="contact-layout" aria-label="Contact options">
    <div class="contact-form-panel"><span class="option-number">01</span><h2>${esc(page.form.title)}</h2><form class="contact-form" data-contact-email="${esc(page.email)}" action="mailto:${esc(page.email)}" method="post" enctype="text/plain"><div class="field-row"><label for="contact-name">Name <span aria-hidden="true">*</span></label><input id="contact-name" name="name" autocomplete="name" required></div><div class="field-row"><label for="contact-email">Email <span aria-hidden="true">*</span></label><input id="contact-email" name="email" type="email" autocomplete="email" required></div><div class="field-row"><label for="contact-organisation">Organisation</label><input id="contact-organisation" name="organisation" autocomplete="organization"></div><div class="field-row"><label for="contact-area">Area of interest</label><select id="contact-area" name="area">${page.form.areas.map(area=>`<option>${esc(area)}</option>`).join('')}</select></div><div class="field-row"><label for="contact-message">Message <span aria-hidden="true">*</span></label><textarea id="contact-message" name="message" rows="6" required></textarea></div><button class="button" type="submit"><span>${esc(page.form.button)}</span>${icon('arrow')}</button><p class="form-note">${esc(page.form.note)}</p><p class="form-status" aria-live="polite"></p></form></div>
    <aside class="direct-contact"><span class="option-number">02</span><span class="direct-icon">${icon('mail')}</span><h2>${esc(page.direct.title)}</h2><p>${esc(page.direct.text)}</p><a class="button button-outline" href="mailto:${esc(page.email)}"><span>${esc(page.direct.button)}</span>${icon('arrow')}</a><a class="contact-email-link" href="mailto:${esc(page.email)}">${esc(page.email)}</a></aside>
  </section>
</main>`;
