import {esc,attrs,img,icon} from '../lib/html.mjs';

const sourceLink=item=>`<a class="source-card" ${attrs(item)}><span><strong>${esc(item.label)}</strong><small>${esc(item.detail)}</small></span>${icon('arrow')}</a>`;

export default page=>`<main id="main" class="subpage-main initiative-page">
  <section class="page-hero initiative-page-hero" aria-labelledby="initiative-page-heading"><div><span class="page-eyebrow">${esc(page.eyebrow)}</span><h1 id="initiative-page-heading">${esc(page.heading)}</h1><p>${esc(page.lead)}</p></div><nav class="page-index" aria-label="Initiative page sections"><a href="#initiative-purpose">Purpose</a><a href="#initiative-commitments">Priorities</a><a href="#conservation-context">Conservation context</a></nav></section>
  <section class="page-cta initiative-full-page-cta" aria-labelledby="initiative-full-page-heading"><div><span class="page-eyebrow">${esc(page.fullPage.eyebrow)}</span><h2 id="initiative-full-page-heading">${esc(page.fullPage.title)}</h2><p>${esc(page.fullPage.text)}</p></div><a class="button" ${attrs(page.fullPage.link)}><span>${esc(page.fullPage.link.label)}</span>${icon('arrow')}</a></section>
  <section id="initiative-purpose" class="page-section initiative-purpose" aria-labelledby="initiative-purpose-heading"><figure class="initiative-page-mark">${img(page.image,'loading="eager"')}</figure><div class="section-copy"><span class="page-eyebrow">${esc(page.purpose.eyebrow)}</span><h2 id="initiative-purpose-heading">${esc(page.purpose.title)}</h2>${page.purpose.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div></section>
  <section id="initiative-commitments" class="page-section initiative-commitments" aria-labelledby="initiative-commitments-heading"><div class="section-heading"><span class="page-eyebrow">Shared biology. Species-specific evidence.</span><h2 id="initiative-commitments-heading">Many species. Blood group systems, known and unknown. One BHOC system. One core design engineered by nature.</h2></div><div class="application-grid">${page.commitments.map(item=>`<article class="application-card"><span class="application-icon">${icon(item.icon)}</span><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></article>`).join('')}</div></section>
  <section id="conservation-context" class="page-section conservation-context" aria-labelledby="conservation-context-heading"><div class="section-heading"><span class="page-eyebrow">${esc(page.conservation.eyebrow)}</span><h2 id="conservation-context-heading">${esc(page.conservation.title)}</h2><p>${esc(page.conservation.text)}</p></div><div class="source-grid conservation-source-grid">${page.conservation.links.map(sourceLink).join('')}</div></section>
  <section class="page-cta" aria-labelledby="initiative-action-heading"><div><span class="page-eyebrow">Species and comparative biology</span><h2 id="initiative-action-heading">${esc(page.action.title)}</h2><p>${esc(page.action.text)}</p></div><a class="button" ${attrs(page.action.link)}><span>${esc(page.action.link.label)}</span>${icon('arrow')}</a></section>
</main>`;
