import {esc,lines,attrs,button,img,icon,section} from '../lib/html.mjs';
const bhoc=text=>esc(text).replace('O','<span class="oxygen-initial">O</span>');
const expansion=text=>text.split(/\s+/).map(word=>`<span><strong>${esc(word[0])}</strong>${esc(word.slice(1))}</span>`).join(' ');
const slides=d=>(d.slides?.length?d.slides:[d.image]);
const slideMarkup=(slide,index)=>img(slide,`${index===0?'fetchpriority="high"':'loading="lazy"'} class="hero-slide${index===0?' is-active':''}" data-hero-slide="${index}" data-hero-label="${esc(slide.label||`Slide ${index+1}`)}" aria-hidden="${index===0?'false':'true'}"`);
const dotMarkup=(slide,index)=>`<button type="button" class="hero-dot${index===0?' is-active':''}" data-hero-slide-to="${index}" aria-label="Show ${esc(slide.label||`slide ${index+1}`)}"${index===0?' aria-current="true"':''}><span></span></button>`;
export default d=>{
  const heroSlides=slides(d);
  return section(d,'hero',`<div class="hero-stage" data-hero-carousel data-hero-interval="${Number(d.intervalMs)||300000}" role="region" aria-roledescription="carousel" aria-label="BHOC Veterinary habitats"><div class="hero-media"><div class="hero-slides">${heroSlides.map(slideMarkup).join('')}</div><div class="hero-wash" aria-hidden="true"></div><button type="button" class="hero-arrow hero-prev" aria-label="Previous hero image">${icon('chevron')}</button><button type="button" class="hero-arrow hero-next" aria-label="Next hero image">${icon('chevron')}</button><div class="hero-dots" role="group" aria-label="Choose hero image">${heroSlides.map(dotMarkup).join('')}</div></div><div class="hero-copy"><h1 id="${d.id}-heading">${lines(d.heading)}</h1><div class="hero-product"><p class="hero-product-line"><span class="hero-abbreviation"><strong>${bhoc(d.product.name)}</strong></span><span class="hero-product-separator" aria-hidden="true">-</span><span class="hero-expansion">${expansion(d.product.expansion)}</span></p></div><p class="hero-intent">${esc(d.intent)}</p><p class="hero-profile">${esc(d.profile)}</p><p class="hero-evidence-note">${esc(d.evidenceNote)}</p><div class="hero-actions">${d.actions.map(button).join('')}</div></div><p class="sr-only" id="hero-announcement" aria-live="polite"></p></div><a class="initiative-mark" ${attrs(d.initiative.link)} aria-label="${esc(d.initiative.link.label)}"><span class="initiative-logo">${img(d.initiative.image,'fetchpriority="high"')}</span><span class="initiative-copy"><strong>${esc(d.initiative.title)}</strong><span class="initiative-tagline">${esc(d.initiative.tagline)}</span><span class="initiative-promise">${esc(d.initiative.promise)}</span><span class="initiative-link">${esc(d.initiative.link.label)} ${icon('arrow')}</span></span></a>`);
};
